#!/usr/bin/env bash
# One-time (and safely re-runnable) setup of the production host.
#
#   scp -r _ops/deploy ubuntu@<host>:/tmp/jayhind-deploy
#   ssh ubuntu@<host> 'bash /tmp/jayhind-deploy/server-bootstrap.sh'
#
# Idempotent: re-running it re-installs the deploy script, pm2 config and nginx
# config from this directory and leaves data (shared/, releases, .env) alone.
# It does NOT write .env files or touch the database — see README.md.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
ROOT=/srv/jayhind
SERVICES=(client-back admin-back client-front admin-front)

echo "== swap (the host has ~1 GB RAM)"
if ! swapon --show | grep -q /swapfile; then
  sudo fallocate -l 2G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile >/dev/null
  sudo swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
fi
echo 'vm.swappiness=10' | sudo tee /etc/sysctl.d/99-jayhind-swap.conf >/dev/null
sudo sysctl -q --system

echo "== packages"
command -v rsync >/dev/null || sudo apt-get install -y -qq rsync
command -v pm2 >/dev/null || sudo npm install -g pm2 --no-audit --no-fund --loglevel=error

echo "== directories"
sudo mkdir -p "$ROOT/bin"
sudo chown ubuntu:ubuntu "$ROOT" "$ROOT/bin"
for s in "${SERVICES[@]}"; do
  mkdir -p "$ROOT/$s/releases" "$ROOT/$s/shared"
done
# nginx (www-data) reads the frontends' files.
chmod 755 "$ROOT" "$ROOT/client-front" "$ROOT/admin-front" \
  "$ROOT/client-front/releases" "$ROOT/admin-front/releases"
# .env files hold the DB password and JWT secrets.
chmod 750 "$ROOT/client-back" "$ROOT/admin-back"

install -m 755 "$here/jayhind-deploy.sh" "$ROOT/bin/jayhind-deploy"
install -m 644 "$here/ecosystem.config.js" "$ROOT/ecosystem.config.js"

echo "== pm2 on boot + log rotation"
sudo env PATH="$PATH" pm2 startup systemd -u ubuntu --hp /home/ubuntu >/dev/null
pm2 describe pm2-logrotate >/dev/null 2>&1 || pm2 install pm2-logrotate >/dev/null
pm2 set pm2-logrotate:max_size 20M >/dev/null
pm2 set pm2-logrotate:retain 14 >/dev/null

echo "== nginx"
sudo mkdir -p /etc/nginx/ssl /etc/nginx/snippets
if [ ! -f /etc/nginx/ssl/aakhaja.com.crt ]; then
  # Self-signed origin certificate — accepted by Cloudflare SSL mode "Full".
  # Replace both files with a Cloudflare Origin Certificate for "Full (strict)".
  sudo openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
    -subj "/CN=aakhaja.com" \
    -addext "subjectAltName=DNS:aakhaja.com,DNS:*.aakhaja.com" \
    -keyout /etc/nginx/ssl/aakhaja.com.key -out /etc/nginx/ssl/aakhaja.com.crt 2>/dev/null
  sudo chmod 600 /etc/nginx/ssl/aakhaja.com.key
fi

# Trust CF-Connecting-IP only from Cloudflare's published ranges (fetched live).
{
  echo "# Generated by server-bootstrap.sh from https://www.cloudflare.com/ips — re-run to refresh."
  for u in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    curl -fsS --max-time 10 "$u" | sed '/^\s*$/d; s/^/set_real_ip_from /; s/$/;/'
  done
  echo "real_ip_header CF-Connecting-IP;"
} > /tmp/cloudflare-realip.conf
grep -q set_real_ip_from /tmp/cloudflare-realip.conf || { echo "could not fetch Cloudflare ranges" >&2; exit 1; }
sudo install -m 644 /tmp/cloudflare-realip.conf /etc/nginx/conf.d/cloudflare-realip.conf

sudo install -m 644 "$here"/nginx/snippets/*.conf /etc/nginx/snippets/
sudo install -m 644 "$here/nginx/jayhind.conf" /etc/nginx/sites-available/jayhind.conf
sudo ln -sfn /etc/nginx/sites-available/jayhind.conf /etc/nginx/sites-enabled/jayhind.conf
sudo rm -f /etc/nginx/sites-enabled/default

# A placeholder so nginx -t passes before the first frontend deploy.
for s in client-front admin-front; do
  if [ ! -e "$ROOT/$s/current" ]; then
    mkdir -p "$ROOT/$s/releases/000-placeholder"
    echo '<!doctype html><title>Deploying…</title>' > "$ROOT/$s/releases/000-placeholder/index.html"
    ln -sfn "$ROOT/$s/releases/000-placeholder" "$ROOT/$s/current"
  fi
done

sudo nginx -t
sudo systemctl reload nginx

echo "== done"
